export const categories_results = [
    {},
    { name: "Brucelosis", result: ".2333"},
    { name: "Chagas", result: ".3333"},
    { name: "FOD", result: ".3333"},
    { name: "Hepatitis A", result: ".3333"},
    { name: "Hepatitis Autoinmune", result: ".3333"},
    { name: "Herpes", result: ".3333"},
    { name: "Influenza", result: ".02"},
    { name: "Meningitis", result: ".5"},
    { name: "Neumonia Neusocomial", result: "1"},
    { name: "Neumonia", result: ".02"},
    { name: "Paludismo", result: ".02"},
    { name: "Rabia", result: ".5"},
    { name: "Salmonelosis", result: "0.02"},
    { name: "Sepsis", result: ".02"},
    { name: "Triquinosis", result: ".02"},
    { name: "Tuberculosis Pulmonar", result: ".2333"},
]